services:
  postgresql:
    container_name: postgresql
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin " ]
      interval: 10s
      timeout: 5s
      retries: 5


  worker_service:
      build: ./worker_service
      ports:
        - '8080:8080'
      depends_on:
        postgresql:
          condition: service_healthy

  tasks_service:
      build: ./tasks_service
      ports:
        - '8081:8081'
      depends_on:
        postgresql:
          condition: service_healthy